DECLARE @NOME VARCHAR(10)
    ,@SOBRENOME VARCHAR(10)
    ,@IDADE INT
    ,@DATA_NASCIMENTO DATE

SET @NOME = 'Ronan'
SET @SOBRENOME = 'Lima'
SET @IDADE = 30
SET @DATA_NASCIMENTO = '1993-01-01'


SELECT @NOME AS Nome
    ,@SOBRENOME AS Sobrenome
    ,@IDADE AS Idade
    ,@DATA_NASCIMENTO AS DataNascimento